import test from 'node:test';
import assert from 'node:assert/strict';
import { resolveReportScope, resolveReportRecordScope } from './report.scope';

test('officers only see their own reports', () => {
  const scope = resolveReportScope({
    userId: 'officer-123',
    role: 'OFFICER',
    email: 'officer@example.com',
  });

  assert.deepEqual(scope, { generatedBy: 'officer-123' });
});

test('admins keep access to all reports', () => {
  const scope = resolveReportScope({
    userId: 'admin-123',
    role: 'ADMIN',
    email: 'admin@example.com',
  });

  assert.equal(scope, undefined);
});

test('an unauthenticated caller gets no scope, so callers must refuse them first', () => {
  // Documents the fail-open shape B-43 exploited: absent a user the helper
  // returns "no restriction", which is why every report controller now goes
  // through requireAuthUser before it reaches this layer.
  assert.equal(resolveReportScope(undefined), undefined);
  assert.equal(resolveReportRecordScope(undefined), undefined);
});

test('a report generated by an officer contains only that officer\'s records', () => {
  const scope = resolveReportRecordScope({
    userId: 'officer-123',
    role: 'OFFICER',
    email: 'officer@example.com',
  });

  assert.deepEqual(scope, { userId: 'officer-123' });
});

test('a report generated by an admin contains every officer\'s records', () => {
  const scope = resolveReportRecordScope({
    userId: 'admin-123',
    role: 'ADMIN',
    email: 'admin@example.com',
  });

  assert.equal(scope, undefined);
});

test('report scope keys off generatedBy, record scope keys off userId', () => {
  // The two rules are the same rule over different columns. Asserting the key
  // names guards the copy-paste hazard of one drifting onto the other's field.
  const officer = {
    userId: 'officer-123',
    role: 'OFFICER' as const,
    email: 'officer@example.com',
  };

  assert.deepEqual(Object.keys(resolveReportScope(officer) ?? {}), ['generatedBy']);
  assert.deepEqual(Object.keys(resolveReportRecordScope(officer) ?? {}), ['userId']);
});
